<!--
An iron-iconset-svg generated by PolyIcon.
https://polyicon.com

Example usage:

    <link rel="import" href="../${font.fontname}-iconset-svg/${font.fontname}-iconset-svg.html">

To use an icon from this sets, first prefix your `iron-icon` with the iconset name "${font.fontname}", 
followed by a colon, ":", and then the icon id. 
    
    <iron-icon icon="${font.fontname}:github"></iron-icon>


### PolyIcon

The fonts in these iconsets were generated by PolyIcon, which is derived from Fontello.

${font.copyright}

@pseudoElement ${font.fontname}-iconset-svg
@demo demo/index.html
-->
<link rel="import" href="./bower_components/iron-icon/iron-icon.html">
<link rel="import" href="./bower_components/iron-iconset-svg/iron-iconset-svg.html">

<iron-iconset-svg size="${font.ascent - font.descent}" name="${font.fontname}">
<svg xmlns="http://www.w3.org/2000/svg">
<defs>
<% glyphs.forEach(function(glyph) { %>
<g id="${glyph.css}"><path d="${glyph.d}"/></g>
<% }); %>
</defs>
</svg>
</iron-iconset-svg>
